/**
 * Ethers v5 compatibility wrapper for Superfluid SDK
 * Re-exports all ethers v6 exports plus BigNumber shim
 */

import * as ethersV6 from 'ethers';
import { BigNumber } from './ethers-shim';

// Re-export BigNumber for v5 compatibility
export { BigNumber };

// Re-export commonly used ethers v6 exports
export const {
  ethers,
  Contract,
  ContractFactory,
  Wallet,
  JsonRpcProvider,
  BrowserProvider,
  formatEther,
  parseEther,
  formatUnits,
  parseUnits,
  keccak256,
  toUtf8Bytes,
  hexlify,
  getAddress,
  isAddress,
  ZeroAddress,
  MaxUint256,
  AbiCoder,
  Interface,
  Fragment,
  FunctionFragment,
  EventFragment,
  Signature,
  Transaction,
  TransactionReceipt,
  TransactionResponse,
  Block,
  Log,
  EventLog,
  VoidSigner,
  AbstractProvider,
  FallbackProvider,
  Network,
  id,
  solidityPacked,
  solidityPackedKeccak256,
  solidityPackedSha256,
  encodeBytes32String,
  decodeBytes32String,
  zeroPadValue,
  getBytes,
  concat,
  dataLength,
  dataSlice,
  stripZerosLeft,
  isBytesLike,
  isHexString,
  toBeHex,
  toQuantity,
  toBigInt,
  toNumber,
  getUint,
  mask,
  toTwos,
  fromTwos,
  sha256,
  ripemd160,
  computeHmac,
  randomBytes,
  pbkdf2,
  scrypt,
  scryptSync,
  lock,
  Mnemonic,
  HDNodeWallet,
  BaseWallet,
  SigningKey,
  computeAddress,
  recoverAddress,
  hashMessage,
  verifyMessage,
  verifyTypedData,
  TypedDataEncoder,
  dnsEncode,
  namehash,
  ensNormalize,
  isValidName,
  resolveAddress,
  getDefaultProvider,
  copyRequest,
  InfuraProvider,
  InfuraWebSocketProvider,
  QuickNodeProvider,
  AnkrProvider,
  AlchemyProvider,
  CloudflareProvider,
  EtherscanProvider,
  PocketProvider,
  IpcSocketProvider,
  SocketProvider,
  WebSocketProvider,
  EnsPlugin,
  EnsResolver,
  FeeDataNetworkPlugin,
  FetchUrlFeeDataNetworkPlugin,
  GasCostPlugin,
  MulticoinProviderPlugin,
  NetworkPlugin,
  FixedNumber,
  FetchRequest,
  FetchResponse,
  FetchCancelSignal,
  decodeRlp,
  encodeRlp,
  accessListify,
  Result,
  Indexed,
  Typed,
  ErrorDescription,
  LogDescription,
  TransactionDescription,
  ConstructorFragment,
  ErrorFragment,
  ParamType,
  ContractEventPayload,
  ContractUnknownEventPayload,
  ContractTransactionReceipt,
  ContractTransactionResponse,
  UndecodedEventLog,
  AbstractSigner,
  NonceManager,
  wordlists,
  WordlistOwl,
  WordlistOwlA,
  LangEn,
  version
} = ethersV6;

// v5-style utils namespace for compatibility
export const utils = {
  formatEther: ethersV6.formatEther,
  parseEther: ethersV6.parseEther,
  formatUnits: ethersV6.formatUnits,
  parseUnits: ethersV6.parseUnits,
  keccak256: ethersV6.keccak256,
  toUtf8Bytes: ethersV6.toUtf8Bytes,
  hexlify: ethersV6.hexlify,
  arrayify: (data: string): Uint8Array => ethersV6.getBytes(data),
  defaultAbiCoder: ethersV6.AbiCoder.defaultAbiCoder(),
  id: ethersV6.id,
  getAddress: ethersV6.getAddress,
  isAddress: ethersV6.isAddress,
  solidityPack: ethersV6.solidityPacked,
  solidityKeccak256: ethersV6.solidityPackedKeccak256,
  soliditySha256: ethersV6.solidityPackedSha256,
  namehash: ethersV6.namehash,
  hashMessage: ethersV6.hashMessage,
  verifyMessage: ethersV6.verifyMessage,
  randomBytes: ethersV6.randomBytes,
  concat: ethersV6.concat,
  zeroPad: ethersV6.zeroPadValue,
};

// v5-style constants namespace for compatibility
export const constants = {
  AddressZero: ethersV6.ZeroAddress,
  HashZero: '0x0000000000000000000000000000000000000000000000000000000000000000',
  MaxUint256: BigNumber.from(ethersV6.MaxUint256.toString()),
  Zero: BigNumber.from(0),
  One: BigNumber.from(1),
  Two: BigNumber.from(2),
  NegativeOne: BigNumber.from(-1),
  WeiPerEther: BigNumber.from('1000000000000000000'),
};

// v5-style providers namespace for compatibility
export const providers = {
  Web3Provider: ethersV6.BrowserProvider,
  JsonRpcProvider: ethersV6.JsonRpcProvider,
  StaticJsonRpcProvider: ethersV6.JsonRpcProvider,
  WebSocketProvider: ethersV6.WebSocketProvider,
  InfuraProvider: ethersV6.InfuraProvider,
  AlchemyProvider: ethersV6.AlchemyProvider,
  getDefaultProvider: ethersV6.getDefaultProvider,
};

// Type exports for compatibility
export type Signer = ethersV6.Signer;
export type Provider = ethersV6.Provider;

// Default export for compatibility
export default ethersV6;
