// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title TitheVerifier
 * @notice Verifies zero-knowledge proofs for anonymous tithing on Bible.fi
 * @dev Integrates with Noir-generated proofs for privacy-preserving donations
 * 
 * Biblical Foundation: Matthew 6:3-4
 * "But when you give to the needy, do not let your left hand know 
 * what your right hand is doing, so that your giving may be in secret."
 */
contract TitheVerifier {
    // Events
    event AnonymousTitheVerified(
        bytes32 indexed commitment,
        bytes32 indexed churchId,
        uint256 minThreshold,
        uint256 timestamp
    );
    
    event ChurchRegistered(
        bytes32 indexed churchId,
        address indexed churchAddress,
        string churchName,
        uint256 timestamp
    );

    // Structs
    struct Church {
        address paymentAddress;
        string name;
        bool isVerified;
        uint256 totalTithesReceived;
        uint256 registrationTime;
    }

    struct TitheRecord {
        bytes32 commitment;
        bytes32 churchId;
        uint256 minThreshold;
        uint256 timestamp;
        bool isUsed;
    }

    // State variables
    mapping(bytes32 => Church) public churches;
    mapping(bytes32 => TitheRecord) public titheRecords;
    mapping(address => uint256) public anonymousTitheCount;
    
    address public admin;
    uint256 public totalAnonymousTithes;

    // Modifiers
    modifier onlyAdmin() {
        require(msg.sender == admin, "Only admin");
        _;
    }

    constructor() {
        admin = msg.sender;
    }

    /**
     * @notice Register a church for anonymous tithe receiving
     * @param churchAddress The payment address for the church
     * @param churchName The name of the church
     */
    function registerChurch(
        address churchAddress,
        string calldata churchName
    ) external onlyAdmin {
        require(churchAddress != address(0), "Invalid church address");
        
        bytes32 churchId = keccak256(abi.encodePacked(churchAddress, churchName));
        
        churches[churchId] = Church({
            paymentAddress: churchAddress,
            name: churchName,
            isVerified: true,
            totalTithesReceived: 0,
            registrationTime: block.timestamp
        });

        emit ChurchRegistered(churchId, churchAddress, churchName, block.timestamp);
    }

    /**
     * @notice Verify and record an anonymous tithe
     * @param proof The zero-knowledge proof generated by Noir
     * @param minThreshold The minimum tithe amount (public)
     * @param churchId The church receiving the tithe (public)
     * @param commitment The commitment to the actual tithe (public)
     * @dev This is a simplified version - full implementation needs UltraPlonk verifier
     */
    function verifyAndRecordTithe(
        bytes calldata proof,
        uint256 minThreshold,
        bytes32 churchId,
        bytes32 commitment
    ) external payable {
        // Verify church is registered
        require(churches[churchId].isVerified, "Church not verified");
        
        // Verify commitment hasn't been used (prevent double-spending)
        require(!titheRecords[commitment].isUsed, "Commitment already used");
        
        // Verify proof (simplified - in production use actual Noir verifier)
        require(verifyProof(proof, minThreshold, churchId, commitment), "Invalid proof");
        
        // Verify sent value meets minimum
        require(msg.value >= minThreshold, "Sent value below minimum");
        
        // Record the tithe
        titheRecords[commitment] = TitheRecord({
            commitment: commitment,
            churchId: churchId,
            minThreshold: minThreshold,
            timestamp: block.timestamp,
            isUsed: true
        });
        
        // Update statistics
        churches[churchId].totalTithesReceived += msg.value;
        anonymousTitheCount[msg.sender]++;
        totalAnonymousTithes++;
        
        // Transfer funds to church
        (bool success, ) = churches[churchId].paymentAddress.call{value: msg.value}("");
        require(success, "Transfer failed");
        
        emit AnonymousTitheVerified(commitment, churchId, minThreshold, block.timestamp);
    }

    /**
     * @notice Verify a Noir-generated proof
     * @dev This is a placeholder - actual implementation requires UltraPlonk verifier
     * The real verifier contract is generated by: nargo codegen-verifier
     */
    function verifyProof(
        bytes calldata proof,
        uint256 minThreshold,
        bytes32 churchId,
        bytes32 commitment
    ) internal pure returns (bool) {
        // PLACEHOLDER: In production, this calls the actual UltraPlonk verifier
        // generated by Noir's codegen-verifier command
        
        // Verify proof is not empty
        require(proof.length > 0, "Empty proof");
        
        // Verify public inputs are valid
        require(minThreshold > 0, "Invalid threshold");
        require(churchId != bytes32(0), "Invalid church ID");
        require(commitment != bytes32(0), "Invalid commitment");
        
        // In production: return UltraVerifier.verify(proof, publicInputs);
        // For now, accept all proofs in development
        return true;
    }

    /**
     * @notice Get church details
     */
    function getChurch(bytes32 churchId) external view returns (Church memory) {
        return churches[churchId];
    }

    /**
     * @notice Get tithe record
     */
    function getTitheRecord(bytes32 commitment) external view returns (TitheRecord memory) {
        return titheRecords[commitment];
    }

    /**
     * @notice Get user's anonymous tithe count
     */
    function getUserTitheCount(address user) external view returns (uint256) {
        return anonymousTitheCount[user];
    }

    /**
     * @notice Update admin
     */
    function updateAdmin(address newAdmin) external onlyAdmin {
        require(newAdmin != address(0), "Invalid admin");
        admin = newAdmin;
    }
}
