// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ZKTithingVerifier
 * @notice Verifies zero-knowledge proofs for anonymous tithing
 * @dev Compatible with Noir-generated proofs for privacy-preserving donations
 * 
 * "But when thou doest alms, let not thy left hand know what thy right hand doeth" - Matthew 6:3
 */
contract ZKTithingVerifier is Ownable {
    // ============ State Variables ============
    
    /// @notice Address of the Ultraplonk verifier contract (generated by Noir)
    address public verifier;
    
    /// @notice Mapping to track used nullifiers (prevents double-spending)
    mapping(bytes32 => bool) public nullifierUsed;
    
    /// @notice Total verified anonymous tithes
    uint256 public totalVerifiedTithes;
    
    /// @notice Total amount verified (in base units)
    uint256 public totalVerifiedAmount;
    
    // ============ Events ============
    
    event TitheVerified(
        bytes32 indexed nullifier,
        address indexed receiver,
        uint256 amount,
        uint256 timestamp
    );
    
    event VerifierUpdated(
        address indexed oldVerifier,
        address indexed newVerifier
    );
    
    event ProofRejected(
        bytes32 indexed nullifier,
        string reason
    );
    
    // ============ Errors ============
    
    error NullifierAlreadyUsed();
    error InvalidProof();
    error VerifierNotSet();
    error InvalidVerifier();
    error InvalidInputLength();
    
    // ============ Constructor ============
    
    constructor(address _verifier) Ownable(msg.sender) {
        verifier = _verifier;
    }
    
    // ============ External Functions ============
    
    /**
     * @notice Verify a tithing proof
     * @param a Proof element a (2 elements)
     * @param b Proof element b (2x2 elements)
     * @param c Proof element c (2 elements)
     * @param input Public inputs [merkleRoot, receiver, expectedAmount, wisdomScore]
     * @param nullifier Unique nullifier for this tithe
     * @return success Whether verification succeeded
     */
    function verifyTithing(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[4] calldata input,
        bytes32 nullifier
    ) external returns (bool success) {
        // Check nullifier hasn't been used
        if (nullifierUsed[nullifier]) {
            emit ProofRejected(nullifier, "Nullifier already used");
            revert NullifierAlreadyUsed();
        }
        
        // Verify the proof using the verifier contract
        if (verifier != address(0)) {
            (bool callSuccess, bytes memory result) = verifier.staticcall(
                abi.encodeWithSignature(
                    "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[4])",
                    a, b, c, input
                )
            );
            
            if (!callSuccess || (result.length > 0 && !abi.decode(result, (bool)))) {
                emit ProofRejected(nullifier, "Invalid proof");
                revert InvalidProof();
            }
        }
        
        // Mark nullifier as used
        nullifierUsed[nullifier] = true;
        
        // Extract receiver and amount from public inputs
        address receiver = address(uint160(input[1]));
        uint256 amount = input[2];
        
        // Update statistics
        totalVerifiedTithes++;
        totalVerifiedAmount += amount;
        
        emit TitheVerified(nullifier, receiver, amount, block.timestamp);
        
        return true;
    }
    
    /**
     * @notice Verify a Noir proof (alternative format)
     * @param proof Raw proof bytes from Noir
     * @param publicInputs Public inputs array
     * @return success Whether verification succeeded
     */
    function verify(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external view returns (bool success) {
        if (verifier == address(0)) revert VerifierNotSet();
        
        // Call the verifier contract with raw proof
        (bool callSuccess, bytes memory result) = verifier.staticcall(
            abi.encodeWithSignature(
                "verify(bytes,uint256[])",
                proof,
                publicInputs
            )
        );
        
        return callSuccess && (result.length == 0 || abi.decode(result, (bool)));
    }
    
    /**
     * @notice Check if a nullifier has been used
     * @param nullifier Nullifier to check
     * @return used Whether the nullifier has been used
     */
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return nullifierUsed[nullifier];
    }
    
    /**
     * @notice Get verification statistics
     * @return _totalTithes Total number of verified tithes
     * @return _totalAmount Total amount verified
     */
    function getStats() external view returns (
        uint256 _totalTithes,
        uint256 _totalAmount
    ) {
        return (totalVerifiedTithes, totalVerifiedAmount);
    }
    
    // ============ Admin Functions ============
    
    /**
     * @notice Update the verifier contract address
     * @param _verifier New verifier address
     */
    function setVerifier(address _verifier) external onlyOwner {
        address oldVerifier = verifier;
        verifier = _verifier;
        emit VerifierUpdated(oldVerifier, _verifier);
    }
}
