
-- Bulk insert US churches from the seeder data
-- Using ON CONFLICT to skip duplicates based on name + city + state_province
INSERT INTO public.global_churches (name, denomination, city, state_province, country, postal_code, website, phone, accepts_crypto, accepts_fiat, accepts_cards, accepts_checks, verified, crypto_networks, fiat_currencies)
VALUES
-- FLORIDA
('First Baptist Church of Mount Dora', 'Baptist', 'Mount Dora', 'Florida', 'United States', '32757', 'https://fbcmountdora.org', '(352) 383-2496', false, true, true, true, true, '{}', '{USD}'),
('Mount Dora First United Methodist Church', 'Methodist', 'Mount Dora', 'Florida', 'United States', '32757', 'https://fumcmountdora.org', '(352) 383-2264', false, true, true, true, true, '{}', '{USD}'),
('St. Patrick Catholic Church', 'Catholic', 'Mount Dora', 'Florida', 'United States', '32757', 'https://stpatrickmtdora.org', '(352) 383-3686', false, true, true, true, true, '{}', '{USD}'),
('Grace Bible Church Mount Dora', 'Non-denominational', 'Mount Dora', 'Florida', 'United States', '32757', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Trinity Lutheran Church Mount Dora', 'Lutheran', 'Mount Dora', 'Florida', 'United States', '32757', NULL, '(352) 383-4153', false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church of Eustis', 'Baptist', 'Eustis', 'Florida', 'United States', '32726', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Eustis First United Methodist Church', 'Methodist', 'Eustis', 'Florida', 'United States', '32726', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('St. Mary of the Lakes Catholic Church', 'Catholic', 'Eustis', 'Florida', 'United States', '32726', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church of Tavares', 'Baptist', 'Tavares', 'Florida', 'United States', '32778', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Tavares First United Methodist', 'Methodist', 'Tavares', 'Florida', 'United States', '32778', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church Umatilla', 'Baptist', 'Umatilla', 'Florida', 'United States', '32784', NULL, NULL, false, true, false, true, true, '{}', '{USD}'),
('Umatilla United Methodist Church', 'Methodist', 'Umatilla', 'Florida', 'United States', '32784', NULL, NULL, false, true, false, true, true, '{}', '{USD}'),
('First Baptist Church of Apopka', 'Baptist', 'Apopka', 'Florida', 'United States', '32703', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('St. Francis of Assisi Catholic Church Apopka', 'Catholic', 'Apopka', 'Florida', 'United States', '32712', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church of Clermont', 'Baptist', 'Clermont', 'Florida', 'United States', '34711', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Real Life Christian Church Clermont', 'Non-denominational', 'Clermont', 'Florida', 'United States', '34711', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('First Baptist Church of Leesburg', 'Baptist', 'Leesburg', 'Florida', 'United States', '34748', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Morrison United Methodist Church', 'Methodist', 'Leesburg', 'Florida', 'United States', '34748', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('The Father''s House', 'Non-denominational', 'Leesburg', 'Florida', 'United States', '34748', 'https://tfhleesburg.com', NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Orlando', 'Baptist', 'Orlando', 'Florida', 'United States', '32801', 'https://firstorlando.com', NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Discovery Church Orlando', 'Non-denominational', 'Orlando', 'Florida', 'United States', '32826', 'https://discoverychurch.com', NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('St. James Cathedral Orlando', 'Catholic', 'Orlando', 'Florida', 'United States', '32801', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church of Winter Garden', 'Baptist', 'Winter Garden', 'Florida', 'United States', '34787', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church of Ocoee', 'Baptist', 'Ocoee', 'Florida', 'United States', '34761', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('New Covenant United Methodist The Villages', 'Methodist', 'The Villages', 'Florida', 'United States', '32162', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('St. Timothy Catholic Church The Villages', 'Catholic', 'The Villages', 'Florida', 'United States', '32159', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church of Ocala', 'Baptist', 'Ocala', 'Florida', 'United States', '34470', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Blessed Trinity Catholic Church Ocala', 'Catholic', 'Ocala', 'Florida', 'United States', '34480', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church Gainesville', 'Baptist', 'Gainesville', 'Florida', 'United States', '32601', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Trinity United Methodist Gainesville', 'Methodist', 'Gainesville', 'Florida', 'United States', '32607', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church Jacksonville', 'Baptist', 'Jacksonville', 'Florida', 'United States', '32202', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Celebration Church Jacksonville', 'Non-denominational', 'Jacksonville', 'Florida', 'United States', '32256', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('First Baptist Church of Tampa', 'Baptist', 'Tampa', 'Florida', 'United States', '33602', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Idlewild Baptist Church', 'Baptist', 'Lutz', 'Florida', 'United States', '33549', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Trinity Church Miami', 'Non-denominational', 'Miami', 'Florida', 'United States', '33137', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Calvary Chapel Fort Lauderdale', 'Calvary Chapel', 'Fort Lauderdale', 'Florida', 'United States', '33309', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('First Baptist Church Crestview', 'Baptist', 'Crestview', 'Florida', 'United States', '32536', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church Marianna', 'Baptist', 'Marianna', 'Florida', 'United States', '32446', NULL, NULL, false, true, false, true, true, '{}', '{USD}'),
('First United Methodist Defuniak Springs', 'Methodist', 'Defuniak Springs', 'Florida', 'United States', '32435', NULL, NULL, false, true, false, true, true, '{}', '{USD}'),
-- COLORADO
('First Baptist Church of Boulder', 'Baptist', 'Boulder', 'Colorado', 'United States', '80302', 'https://fbcboulder.org', NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('St. John''s Episcopal Church Boulder', 'Episcopal', 'Boulder', 'Colorado', 'United States', '80302', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Sacred Heart of Mary Catholic Church', 'Catholic', 'Boulder', 'Colorado', 'United States', '80303', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Flatirons Community Church', 'Non-denominational', 'Lafayette', 'Colorado', 'United States', '80026', 'https://flatironschurch.com', NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('New Life Church', 'Non-denominational', 'Colorado Springs', 'Colorado', 'United States', '80920', 'https://newlifechurch.org', NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Timberline Church', 'Non-denominational', 'Fort Collins', 'Colorado', 'United States', '80525', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
-- TEXAS
('Gateway Church', 'Non-denominational', 'Southlake', 'Texas', 'United States', '76092', 'https://gatewaypeople.com', NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Prestonwood Baptist Church', 'Baptist', 'Plano', 'Texas', 'United States', '75024', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('First Baptist Dallas', 'Baptist', 'Dallas', 'Texas', 'United States', '75201', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Austin Stone Community Church', 'Non-denominational', 'Austin', 'Texas', 'United States', '78701', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Cornerstone Church', 'Non-denominational', 'San Antonio', 'Texas', 'United States', '78249', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Watermark Community Church', 'Non-denominational', 'Dallas', 'Texas', 'United States', '75248', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('The Village Church Flower Mound', 'Baptist', 'Flower Mound', 'Texas', 'United States', '75028', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Stonebriar Community Church', 'Non-denominational', 'Frisco', 'Texas', 'United States', '75034', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Woodlands Church', 'Non-denominational', 'The Woodlands', 'Texas', 'United States', '77380', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
-- CALIFORNIA
('Hillsong LA', 'Pentecostal', 'Los Angeles', 'California', 'United States', '90028', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('The Rock Church', 'Non-denominational', 'San Diego', 'California', 'United States', '92121', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('City Church San Francisco', 'Non-denominational', 'San Francisco', 'California', 'United States', '94114', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Mariners Church', 'Non-denominational', 'Irvine', 'California', 'United States', '92618', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Reality LA', 'Non-denominational', 'Los Angeles', 'California', 'United States', '90027', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
-- NEW YORK
('Hillsong NYC', 'Pentecostal', 'New York', 'New York', 'United States', '10001', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Brooklyn Tabernacle', 'Non-denominational', 'Brooklyn', 'New York', 'United States', '11201', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Times Square Church', 'Non-denominational', 'New York', 'New York', 'United States', '10019', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Redeemer Presbyterian Church', 'Presbyterian', 'New York', 'New York', 'United States', '10021', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('The Chapel Buffalo', 'Non-denominational', 'Buffalo', 'New York', 'United States', '14217', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
-- GEORGIA
('North Point Community Church', 'Non-denominational', 'Alpharetta', 'Georgia', 'United States', '30022', 'https://northpoint.org', NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Buckhead Church', 'Non-denominational', 'Atlanta', 'Georgia', 'United States', '30305', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('First Baptist Atlanta', 'Baptist', 'Atlanta', 'Georgia', 'United States', '30309', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Passion City Church', 'Non-denominational', 'Atlanta', 'Georgia', 'United States', '30318', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('12Stone Church', 'Non-denominational', 'Lawrenceville', 'Georgia', 'United States', '30043', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
-- OTHER MAJOR CHURCHES
('Willow Creek Community Church', 'Non-denominational', 'South Barrington', 'Illinois', 'United States', '60010', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Cross Point Church', 'Non-denominational', 'Nashville', 'Tennessee', 'United States', '37203', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Elevation Church', 'Baptist', 'Charlotte', 'North Carolina', 'United States', '28277', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Dream City Church', 'Non-denominational', 'Phoenix', 'Arizona', 'United States', '85027', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Christ''s Church of the Valley', 'Non-denominational', 'Peoria', 'Arizona', 'United States', '85383', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Crossroads Church', 'Non-denominational', 'Cincinnati', 'Ohio', 'United States', '45208', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Mars Hill Church', 'Non-denominational', 'Seattle', 'Washington', 'United States', '98121', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Imago Dei Community', 'Non-denominational', 'Portland', 'Oregon', 'United States', '97214', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Kensington Community Church', 'Non-denominational', 'Troy', 'Michigan', 'United States', '48084', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Calvary Chapel Philadelphia', 'Calvary Chapel', 'Philadelphia', 'Pennsylvania', 'United States', '19103', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('McLean Bible Church', 'Non-denominational', 'Vienna', 'Virginia', 'United States', '22182', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Bethlehem Baptist Church', 'Baptist', 'Minneapolis', 'Minnesota', 'United States', '55407', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Elmbrook Church', 'Non-denominational', 'Brookfield', 'Wisconsin', 'United States', '53045', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Central Christian Church', 'Non-denominational', 'Las Vegas', 'Nevada', 'United States', '89011', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Calvary Albuquerque', 'Calvary Chapel', 'Albuquerque', 'New Mexico', 'United States', '87109', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('New Hope Oahu', 'Non-denominational', 'Honolulu', 'Hawaii', 'United States', '96814', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('NewSpring Church', 'Non-denominational', 'Anderson', 'South Carolina', 'United States', '29621', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Southeast Christian Church', 'Christian Church', 'Louisville', 'Kentucky', 'United States', '40229', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Northview Church', 'Non-denominational', 'Carmel', 'Indiana', 'United States', '46033', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('James River Church', 'Assemblies of God', 'Springfield', 'Missouri', 'United States', '65804', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('Christ Community Church', 'Non-denominational', 'Omaha', 'Nebraska', 'United States', '68144', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('First Baptist Church in America', 'Baptist', 'Providence', 'Rhode Island', 'United States', '02903', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('Park Street Church', 'Congregational', 'Boston', 'Massachusetts', 'United States', '02108', NULL, NULL, false, true, true, true, true, '{}', '{USD}'),
('First Baptist Church Jackson', 'Baptist', 'Jackson', 'Wyoming', 'United States', '83001', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('First United Methodist Sun Valley', 'Methodist', 'Sun Valley', 'Idaho', 'United States', '83353', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('First United Methodist Park City', 'Methodist', 'Park City', 'Utah', 'United States', '84060', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}'),
('First United Methodist Lake Tahoe', 'Methodist', 'Incline Village', 'Nevada', 'United States', '89451', NULL, NULL, true, true, true, true, true, '{Base,Ethereum}', '{USD}')
ON CONFLICT DO NOTHING;
