
INSERT INTO biblical_knowledge_base (verse_text, reference, category, principle, application, defi_relevance, financial_keywords)
VALUES
-- Stewardship & Wisdom (additional)
('The blessing of the LORD, it maketh rich, and he addeth no sorrow with it.', 'Proverbs 10:22', 'stewardship_and_wisdom', 'True wealth comes from God without grief', 'Seek investments that build sustainably without ethical compromise', 'Aligned with long-term DeFi strategies that avoid ponzi-like schemes', ARRAY['wealth', 'blessing', 'riches']),
('A good man leaveth an inheritance to his children''s children: and the wealth of the sinner is laid up for the just.', 'Proverbs 13:22', 'stewardship_and_wisdom', 'Generational wealth planning', 'Build portfolios that serve future generations', 'Long-term staking and yield compounding for generational wealth', ARRAY['inheritance', 'wealth', 'generational']),
('Seest thou a man diligent in his business? he shall stand before kings; he shall not stand before mean men.', 'Proverbs 22:29', 'stewardship_and_wisdom', 'Excellence in work leads to promotion', 'Apply diligence to financial research and DeFi strategy', 'Thorough protocol research and due diligence before investing', ARRAY['diligent', 'business', 'work']),
('He that tilleth his land shall have plenty of bread: but he that followeth after vain persons shall have poverty enough.', 'Proverbs 28:19', 'stewardship_and_wisdom', 'Productive work yields abundance', 'Focus on productive yield farming over speculative memecoins', 'Legitimate yield farming vs speculative token chasing', ARRAY['tilleth', 'land', 'plenty', 'poverty']),
('Where no counsel is, the people fall: but in the multitude of counsellors there is safety.', 'Proverbs 11:14', 'stewardship_and_wisdom', 'Seek wise counsel before acting', 'Consult community wisdom before major DeFi decisions', 'Governance voting and community-driven protocol decisions', ARRAY['counsel', 'people', 'fall', 'counsellors', 'safety']),
('The simple believeth every word: but the prudent man looketh well to his going.', 'Proverbs 14:15', 'stewardship_and_wisdom', 'Do not believe every claim', 'Verify protocol audits, team credibility, and tokenomics', 'DYOR: verify smart contract audits before depositing funds', ARRAY['simple', 'believeth', 'prudent', 'looketh']),
('Whatsoever thy hand findeth to do, do it with thy might; for there is no work, nor device, nor knowledge, nor wisdom, in the grave, whither thou goest.', 'Ecclesiastes 9:10', 'stewardship_and_wisdom', 'Work with full effort while you can', 'Actively manage and optimize DeFi positions', 'Active yield optimization and regular portfolio rebalancing', ARRAY['hand', 'might', 'work', 'knowledge', 'wisdom']),
('The hand of the diligent shall bear rule: but the slothful shall be under tribute.', 'Proverbs 12:24', 'stewardship_and_wisdom', 'Diligence leads to authority', 'Consistent DeFi engagement builds expertise and governance power', 'Earn governance tokens through active protocol participation', ARRAY['diligent', 'rule', 'slothful', 'tribute']),

-- Saving & Investment (additional)
('Go to the ant, thou sluggard; consider her ways, and be wise: Which having no guide, overseer, or ruler, Provideth her meat in the summer, and gathereth her food in the harvest.', 'Proverbs 6:6-8', 'saving_and_investment', 'Save during times of abundance', 'Automate savings and build reserves during bull markets', 'Auto-compounding vaults and reserve strategies for bear markets', ARRAY['ant', 'saving', 'harvest', 'provision']),
('There is treasure to be desired and oil in the dwelling of the wise; but a foolish man spendeth it up.', 'Proverbs 21:20', 'saving_and_investment', 'The wise save, the foolish spend all', 'Maintain emergency reserves and avoid over-leveraging', 'Keep stablecoin reserves and avoid full portfolio exposure', ARRAY['treasure', 'wise', 'foolish', 'spendeth']),
('He that is faithful in that which is least is faithful also in much: and he that is unjust in the least is unjust also in much.', 'Luke 16:10', 'saving_and_investment', 'Start small and grow faithfully', 'Begin with small DeFi positions and scale with experience', 'Start with low-risk stablecoin pools before advanced strategies', ARRAY['faithful', 'least', 'much']),
('In the morning sow thy seed, and in the evening withhold not thine hand: for thou knowest not whether shall prosper, either this or that.', 'Ecclesiastes 11:6', 'saving_and_investment', 'Diversify your efforts', 'Spread investments across multiple protocols and strategies', 'Multi-protocol diversification to manage smart contract risk', ARRAY['morning', 'sow', 'evening', 'prosper', 'diversify']),
('He that gathereth in summer is a wise son: but he that sleepeth in harvest is a son that causeth shame.', 'Proverbs 10:5', 'saving_and_investment', 'Act during opportunity windows', 'Capitalize on DeFi opportunities during favorable market conditions', 'Time-sensitive yield farming during liquidity mining events', ARRAY['gathereth', 'summer', 'wise', 'harvest', 'shame']),
('The thoughts of the diligent tend only to plenteousness; but of every one that is hasty only to want.', 'Proverbs 21:5', 'saving_and_investment', 'Careful planning leads to abundance', 'Plan DeFi strategies carefully rather than rushing into positions', 'Research-driven investment thesis over FOMO-driven entries', ARRAY['diligent', 'plenteousness', 'hasty', 'want']),

-- Debt & Borrowing (additional)
('My son, if thou be surety for thy friend, if thou hast stricken thy hand with a stranger, Thou art snared with the words of thy mouth.', 'Proverbs 6:1-2', 'debt_and_borrowing', 'Be cautious with guarantees', 'Avoid guaranteeing others'' DeFi positions', 'Risks of co-signing or providing collateral for others in DeFi', ARRAY['surety', 'friend', 'stranger', 'snared']),
('The rich ruleth over the poor, and the borrower is servant to the lender.', 'Proverbs 22:7', 'debt_and_borrowing', 'Debt creates servitude', 'Minimize leveraged positions in DeFi lending protocols', 'Monitor health factors and maintain safe collateral ratios', ARRAY['rich', 'poor', 'borrower', 'servant', 'lender']),

-- Tithing & Giving (additional)
('Upon the first day of the week let every one of you lay by him in store, as God hath prospered him.', '1 Corinthians 16:2', 'tithing_and_giving', 'Regular systematic giving', 'Set up automated tithe streams proportional to income', 'Superfluid streaming for consistent automated tithing', ARRAY['first day', 'store', 'prospered', 'giving']),
('But this I say, He which soweth sparingly shall reap also sparingly; and he which soweth bountifully shall reap also bountifully.', '2 Corinthians 9:6', 'tithing_and_giving', 'Generous giving brings generous returns', 'Increase giving as DeFi yields grow', 'Percentage-based tithe increases tied to yield performance', ARRAY['soweth', 'reap', 'sparingly', 'bountifully']),
('Will a man rob God? Yet ye have robbed me. But ye say, Wherein have we robbed thee? In tithes and offerings.', 'Malachi 3:8', 'tithing_and_giving', 'Withholding tithes robs God', 'Prioritize tithing before portfolio reinvestment', 'Auto-routing tithe percentage before yield compounding', ARRAY['rob', 'God', 'tithes', 'offerings']),

-- Contentment & Ethics (additional)
('He that loveth silver shall not be satisfied with silver; nor he that loveth abundance with increase.', 'Ecclesiastes 5:10', 'contentment_and_ethics', 'Money alone never satisfies', 'Balance financial growth with spiritual growth', 'Set profit targets and practice taking profits wisely', ARRAY['silver', 'satisfied', 'abundance', 'increase']),
('Labour not to be rich: cease from thine own wisdom. Wilt thou set thine eyes upon that which is not? for riches certainly make themselves wings; they fly away as an eagle toward heaven.', 'Proverbs 23:4-5', 'contentment_and_ethics', 'Do not exhaust yourself pursuing riches', 'Maintain work-life-faith balance in DeFi activities', 'Set stop-losses and avoid obsessive chart-watching', ARRAY['labour', 'rich', 'wisdom', 'wings', 'fly']),
('But godliness with contentment is great gain. For we brought nothing into this world, and it is certain we can carry nothing out.', '1 Timothy 6:6-7', 'contentment_and_ethics', 'Godliness with contentment is true wealth', 'Set realistic yield expectations and avoid greed-driven decisions', 'Avoid chasing unsustainable APYs driven by token emissions', ARRAY['godliness', 'contentment', 'gain', 'world']),
('Better is a little with righteousness than great revenues without right.', 'Proverbs 16:8', 'contentment_and_ethics', 'Righteous small gains beat dishonest large ones', 'Prefer ethical protocols over higher-yielding risky ones', 'Choose audited protocols with fair tokenomics over unaudited high-APY farms', ARRAY['little', 'righteousness', 'revenues', 'right']),
('He that hasteth to be rich hath an evil eye, and considereth not that poverty shall come upon him.', 'Proverbs 28:22', 'contentment_and_ethics', 'Get-rich-quick schemes lead to poverty', 'Avoid FOMO and speculative ape-ins', 'Resist pump-and-dump schemes and unsustainable yield farms', ARRAY['hasteth', 'rich', 'evil eye', 'poverty']),
('Thou shalt not have in thy bag divers weights, a great and a small.', 'Deuteronomy 25:13', 'contentment_and_ethics', 'Use honest measures in all dealings', 'Ensure transparent pricing and fair exchange rates', 'Use DEX aggregators for best execution and avoid hidden fees', ARRAY['weights', 'bag', 'divers', 'honest']),

-- Taxes & Governance (additional)
('For for this cause pay ye tribute also: for they are God''s ministers, attending continually upon this very thing.', 'Romans 13:6', 'taxes_and_governance', 'Pay taxes as civic duty', 'Properly report and pay taxes on all DeFi gains', 'Track all swaps, yields, and capital gains for tax compliance', ARRAY['tribute', 'ministers', 'taxes']),
('And Jesus answering said unto them, Render to Caesar the things that are Caesar''s, and to God the things that are God''s.', 'Mark 12:17', 'taxes_and_governance', 'Fulfill both civic and spiritual obligations', 'Pay taxes AND tithe from DeFi earnings', 'Dual-track tax compliance and tithing from on-chain earnings', ARRAY['render', 'Caesar', 'God']),
('Submit yourselves to every ordinance of man for the Lord''s sake: whether it be to the king, as supreme.', '1 Peter 2:13', 'taxes_and_governance', 'Respect governing authorities', 'Comply with regulatory requirements for DeFi activities', 'KYC/AML compliance and regulatory awareness for DeFi users', ARRAY['submit', 'ordinance', 'king', 'supreme']),

-- Generosity & Charity (additional)
('Charge them that are rich in this world, that they be not highminded, nor trust in uncertain riches, but in the living God, who giveth us richly all things to enjoy.', '1 Timothy 6:17', 'generosity_and_charity', 'Do not trust in uncertain riches', 'Use DeFi wealth for Kingdom impact, not self-glory', 'Redirect DeFi profits toward missions and charitable giving', ARRAY['rich', 'highminded', 'uncertain riches', 'living God']),
('Sell that ye have, and give alms; provide yourselves bags which wax not old, a treasure in the heavens that faileth not.', 'Luke 12:33', 'generosity_and_charity', 'Heavenly treasure outlasts earthly wealth', 'Balance accumulation with generous giving', 'Allocate percentage of DeFi portfolio to charitable smart contracts', ARRAY['sell', 'alms', 'bags', 'treasure', 'heavens']),
('Whoso stoppeth his ears at the cry of the poor, he also shall cry himself, but shall not be heard.', 'Proverbs 21:13', 'generosity_and_charity', 'Ignoring the poor brings consequences', 'Include charitable allocation in every DeFi strategy', 'Charity pool contributions as part of yield distribution', ARRAY['ears', 'cry', 'poor', 'heard']),
('Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over.', 'Luke 6:38', 'generosity_and_charity', 'Generous giving returns abundantly', 'Tithe generously and trust God for provision', 'Tithe-boosted APY multipliers reward generous givers', ARRAY['give', 'measure', 'pressed', 'running over'])

ON CONFLICT DO NOTHING;
