
INSERT INTO biblical_knowledge_base (verse_text, reference, category, principle, application, defi_relevance, financial_keywords)
VALUES
-- STEWARDSHIP (expanded)
('Moreover it is required in stewards, that a man be found faithful.', '1 Corinthians 4:2', 'stewardship_and_wisdom', 'Faithfulness is the measure of stewardship', 'Manage DeFi positions with consistent accountability', 'Smart contract governance requires faithful stewardship of protocol funds', ARRAY['stewards', 'faithful', 'required']),
('His lord said unto him, Well done, thou good and faithful servant: thou hast been faithful over a few things, I will make thee ruler over many things.', 'Matthew 25:21', 'stewardship_and_wisdom', 'Faithful small management leads to greater responsibility', 'Start with small DeFi positions and grow with proven faithfulness', 'Progressive position sizing based on demonstrated competence', ARRAY['faithful', 'servant', 'ruler', 'few things', 'many things']),
('For unto every one that hath shall be given, and he shall have abundance: but from him that hath not shall be taken away even that which he hath.', 'Matthew 25:29', 'stewardship_and_wisdom', 'Use it or lose it principle', 'Actively deploy capital rather than letting it sit idle', 'Idle capital loses value to inflation; deploy in yield-bearing positions', ARRAY['given', 'abundance', 'taken away']),
('The soul of the sluggard desireth, and hath nothing: but the soul of the diligent shall be made fat.', 'Proverbs 13:4', 'stewardship_and_wisdom', 'Diligence produces results, laziness produces nothing', 'Research and actively manage your DeFi portfolio', 'Active yield optimization outperforms passive holding', ARRAY['sluggard', 'diligent', 'nothing', 'fat']),
('Prepare thy work without, and make it fit in the field; and afterwards build thine house.', 'Proverbs 24:27', 'stewardship_and_wisdom', 'Establish income before spending', 'Build yield-generating positions before luxury spending', 'Establish stable yield streams before leveraged or speculative positions', ARRAY['prepare', 'work', 'field', 'build', 'house']),
('Which of you, intending to build a tower, sitteth not down first, and counteth the cost, whether he have sufficient to finish it?', 'Luke 14:28', 'stewardship_and_wisdom', 'Count the cost before committing', 'Calculate total costs including gas, slippage, and IL before entering positions', 'Full cost analysis for DeFi transactions including gas optimization', ARRAY['build', 'tower', 'cost', 'sufficient']),
('So then every one of us shall give account of himself to God.', 'Romans 14:12', 'stewardship_and_wisdom', 'We are accountable for our financial decisions', 'Keep detailed records of all DeFi transactions', 'On-chain transaction history provides accountability and audit trail', ARRAY['account', 'give', 'God']),

-- SAVING & INVESTMENT (expanded)
('Cast thy bread upon the waters: for thou shalt find it after many days.', 'Ecclesiastes 11:1', 'saving_and_investment', 'Invest widely and patiently', 'Diversify across protocols and be patient for returns', 'Multi-protocol diversification with long time horizons', ARRAY['cast', 'bread', 'waters', 'many days']),
('Give a portion to seven, and also to eight; for thou knowest not what evil shall be upon the earth.', 'Ecclesiastes 11:2', 'saving_and_investment', 'Diversify across seven or eight investments', 'Spread risk across 7-8 different DeFi protocols', 'Biblical basis for portfolio diversification across protocols', ARRAY['portion', 'seven', 'eight', 'evil', 'earth']),
('A feast is made for laughter, and wine maketh merry: but money answereth all things.', 'Ecclesiastes 10:19', 'saving_and_investment', 'Money is a practical tool for meeting needs', 'Maintain adequate liquidity for life necessities', 'Keep stablecoin reserves for unexpected needs and opportunities', ARRAY['money', 'answereth', 'all things']),
('The wise man''s eyes are in his head; but the fool walketh in darkness.', 'Ecclesiastes 2:14', 'saving_and_investment', 'Wisdom provides foresight; foolishness leads to blindness', 'Research market conditions before entering positions', 'Use analytics dashboards and market data for informed decisions', ARRAY['wise', 'eyes', 'fool', 'darkness']),
('By much slothfulness the building decayeth; and through idleness of the hands the house droppeth through.', 'Ecclesiastes 10:18', 'saving_and_investment', 'Neglect leads to decay of wealth', 'Regularly maintain and rebalance DeFi positions', 'Monitor health factors, claim rewards, and rebalance regularly', ARRAY['slothfulness', 'building', 'decayeth', 'idleness']),
('For riches are not for ever: and doth the crown endure to every generation?', 'Proverbs 27:24', 'saving_and_investment', 'Wealth is temporary; plan accordingly', 'Build sustainable strategies, not one-time gains', 'Sustainable yield farming over short-term incentive mining', ARRAY['riches', 'forever', 'crown', 'generation']),

-- DEBT & BORROWING (expanded)
('Be not thou one of them that strike hands, or of them that are sureties for debts.', 'Proverbs 22:26', 'debt_and_borrowing', 'Avoid becoming guarantor for debts', 'Never co-sign or guarantee others'' DeFi loans', 'Avoid shared collateral positions and guarantor roles in lending', ARRAY['sureties', 'debts', 'strike hands']),
('The LORD shall open unto thee his good treasure, the heaven to give the rain unto thy land in his season, and to bless all the work of thine hand: and thou shalt lend unto many nations, and thou shalt not borrow.', 'Deuteronomy 28:12', 'debt_and_borrowing', 'God''s blessing enables lending, not borrowing', 'Build enough capital to become a lender, not borrower', 'Supply-side participation in lending protocols is preferred', ARRAY['treasure', 'lend', 'borrow', 'nations', 'bless']),
('Let no man deceive you with vain words: for because of these things cometh the wrath of God upon the children of disobedience.', 'Ephesians 5:6', 'debt_and_borrowing', 'Do not be deceived by empty financial promises', 'Verify all yield claims and tokenomics before investing', 'Reject unrealistic APY promises and verify on-chain data', ARRAY['deceive', 'vain words', 'wrath']),

-- TITHING & GIVING (expanded)
('Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing.', 'Malachi 3:10', 'tithing_and_giving', 'Test God''s faithfulness through tithing', 'Tithe consistently and watch God provide abundantly', 'Automated Superfluid tithe streams with yield-boosted returns', ARRAY['tithes', 'storehouse', 'windows', 'heaven', 'blessing', 'pour']),
('Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver.', '2 Corinthians 9:7', 'tithing_and_giving', 'Give willingly from the heart', 'Set giving levels you can sustain joyfully', 'Customizable tithe percentages that users set voluntarily', ARRAY['purposeth', 'heart', 'give', 'grudgingly', 'cheerful', 'giver']),
('And all the tithe of the land, whether of the seed of the land, or of the fruit of the tree, is the LORD''s: it is holy unto the LORD.', 'Leviticus 27:30', 'tithing_and_giving', 'The tithe belongs to God', 'Tithe is not optional; it is returning what belongs to God', 'First 10% of all yield claims routed to tithe destinations', ARRAY['tithe', 'land', 'seed', 'fruit', 'holy', 'LORD']),
('And he looked up, and saw the rich men casting their gifts into the treasury. And he saw also a certain poor widow casting in thither two mites. And he said, Of a truth I say unto you, that this poor widow hath cast in more than they all.', 'Luke 21:1-3', 'tithing_and_giving', 'God values proportional generosity over absolute amounts', 'Give proportionally regardless of portfolio size', 'Percentage-based tithing ensures fairness across all portfolio sizes', ARRAY['rich', 'gifts', 'treasury', 'widow', 'mites', 'more']),
('He that hath a bountiful eye shall be blessed; for he giveth of his bread to the poor.', 'Proverbs 22:9', 'tithing_and_giving', 'Generous people receive blessing', 'Share DeFi knowledge and yields with those in need', 'Charity pool allocations and community education programs', ARRAY['bountiful', 'blessed', 'bread', 'poor']),

-- CONTENTMENT & ETHICS (expanded)
('Keep thy heart with all diligence; for out of it are the issues of life.', 'Proverbs 4:23', 'contentment_and_ethics', 'Guard your motivations in finance', 'Examine whether greed or wisdom drives your DeFi decisions', 'Wisdom Score evaluation of investment motivations', ARRAY['heart', 'diligence', 'issues', 'life']),
('A good name is rather to be chosen than great riches, and loving favour rather than silver and gold.', 'Proverbs 22:1', 'contentment_and_ethics', 'Reputation exceeds wealth', 'Choose ethical protocols over high-yield dubious ones', 'Protocol reputation and audit status should outweigh APY alone', ARRAY['good name', 'riches', 'favour', 'silver', 'gold']),
('For the love of money is the root of all evil: which while some coveted after, they have erred from the faith.', '1 Timothy 6:10', 'contentment_and_ethics', 'Love of money corrupts', 'Use DeFi as a tool, not an idol', 'Guard against addictive trading behavior and greed-driven decisions', ARRAY['love', 'money', 'root', 'evil', 'coveted', 'faith']),
('Remove far from me vanity and lies: give me neither poverty nor riches; feed me with food convenient for me.', 'Proverbs 30:8', 'contentment_and_ethics', 'Seek balanced provision, not extremes', 'Set reasonable yield targets and risk limits', 'Balanced portfolio allocation between safety and growth', ARRAY['vanity', 'lies', 'poverty', 'riches', 'food', 'convenient']),
('He that is greedy of gain troubleth his own house; but he that hateth gifts shall live.', 'Proverbs 15:27', 'contentment_and_ethics', 'Greed destroys households', 'Do not let DeFi speculation damage family finances', 'Never invest essential family funds in high-risk DeFi strategies', ARRAY['greedy', 'gain', 'troubleth', 'house', 'gifts']),
('Bread of deceit is sweet to a man; but afterwards his mouth shall be filled with gravel.', 'Proverbs 20:17', 'contentment_and_ethics', 'Ill-gotten gains turn bitter', 'Avoid exploitative DeFi tactics like sandwich attacks', 'Reject MEV exploitation and front-running as unethical gains', ARRAY['deceit', 'sweet', 'gravel', 'bread']),

-- TAXES & GOVERNANCE (expanded)
('Let every soul be subject unto the higher powers. For there is no power but of God: the powers that be are ordained of God.', 'Romans 13:1', 'taxes_and_governance', 'Respect governing authorities', 'Comply with all financial regulations and tax requirements', 'Full regulatory compliance for DeFi activities and reporting', ARRAY['subject', 'powers', 'God', 'ordained']),
('Render therefore to all their dues: tribute to whom tribute is due; custom to whom custom; fear to whom fear; honour to whom honour.', 'Romans 13:7', 'taxes_and_governance', 'Pay every obligation due', 'Pay all taxes, fees, and obligations from DeFi earnings', 'Comprehensive tax tracking for all on-chain transactions', ARRAY['render', 'dues', 'tribute', 'custom', 'fear', 'honour']),

-- GENEROSITY & CHARITY (expanded)
('He that hath pity upon the poor lendeth unto the LORD; and that which he hath given will he pay him again.', 'Proverbs 19:17', 'generosity_and_charity', 'Giving to the poor is lending to God', 'Allocate portion of yields to charitable causes', 'Charity pool contributions from yield farming proceeds', ARRAY['pity', 'poor', 'lendeth', 'LORD', 'pay']),
('The liberal soul shall be made fat: and he that watereth shall be watered also himself.', 'Proverbs 11:25', 'generosity_and_charity', 'Generosity brings personal abundance', 'Be generous with DeFi gains and knowledge sharing', 'Community rewards for generous contributors and educators', ARRAY['liberal', 'soul', 'fat', 'watereth', 'watered']),
('If thine enemy be hungry, give him bread to eat; and if he be thirsty, give him water to drink.', 'Proverbs 25:21', 'generosity_and_charity', 'Extend generosity even to adversaries', 'Support community members regardless of disagreements', 'Inclusive DeFi education and charitable giving programs', ARRAY['enemy', 'hungry', 'bread', 'thirsty', 'water']),
('Is it not to deal thy bread to the hungry, and that thou bring the poor that are cast out to thy house? when thou seest the naked, that thou cover him.', 'Isaiah 58:7', 'generosity_and_charity', 'True giving meets practical needs', 'Direct DeFi gains toward tangible community impact', 'Impact-measured charitable allocations from protocol yields', ARRAY['bread', 'hungry', 'poor', 'house', 'naked', 'cover']),

-- JUSTICE & FAIR DEALING (new category)
('Ye shall do no unrighteousness in judgment, in meteyard, in weight, or in measure. Just balances, just weights, a just ephah, and a just hin, shall ye have.', 'Leviticus 19:35-36', 'justice_and_fair_dealing', 'Use honest measures in all transactions', 'Ensure fair pricing and transparent fee structures', 'Fair swap rates, transparent fees, and honest APY reporting', ARRAY['unrighteousness', 'judgment', 'balances', 'weights', 'measure', 'just']),
('Divers weights, and divers measures, both of them are alike abomination to the LORD.', 'Proverbs 20:10', 'justice_and_fair_dealing', 'Double standards in dealing are abomination', 'Apply same standards to all DeFi counterparties', 'Equal treatment in protocol governance and fee structures', ARRAY['divers', 'weights', 'measures', 'abomination']),
('He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?', 'Micah 6:8', 'justice_and_fair_dealing', 'God requires justice, mercy, and humility', 'Practice fair dealing and compassion in all financial transactions', 'Ethical DeFi participation: fair governance votes, merciful lending terms', ARRAY['justly', 'mercy', 'humbly', 'God', 'require']),
('The getting of treasures by a lying tongue is a vanity tossed to and fro of them that seek death.', 'Proverbs 21:6', 'justice_and_fair_dealing', 'Dishonest profit leads to destruction', 'Never misrepresent yields, risks, or protocol capabilities', 'Honest communication about DeFi risks and realistic return expectations', ARRAY['treasures', 'lying', 'tongue', 'vanity', 'death']),
('Woe unto him that buildeth his house by unrighteousness, and his chambers by wrong; that useth his neighbour''s service without wages, and giveth him not for his work.', 'Jeremiah 22:13', 'justice_and_fair_dealing', 'Pay fair wages for all work', 'Compensate contributors and auditors fairly', 'Fair token distribution and contributor compensation in protocols', ARRAY['unrighteousness', 'wrong', 'wages', 'work', 'neighbour']),

-- WISDOM & COUNSEL (new category)
('Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.', 'Proverbs 4:7', 'wisdom_and_counsel', 'Wisdom is the most valuable asset', 'Invest in DeFi education before investing capital', 'Biblical DeFi education modules increase Wisdom Score', ARRAY['wisdom', 'principal', 'getting', 'understanding']),
('The way of a fool is right in his own eyes: but he that hearkeneth unto counsel is wise.', 'Proverbs 12:15', 'wisdom_and_counsel', 'Wise people seek counsel', 'Consult community and advisors before major DeFi moves', 'Governance discussion forums and community-driven decision making', ARRAY['fool', 'right', 'eyes', 'counsel', 'wise']),
('Without counsel purposes are disappointed: but in the multitude of counsellors they are established.', 'Proverbs 15:22', 'wisdom_and_counsel', 'Plans succeed with many advisors', 'Use multiple information sources for DeFi strategy', 'Multi-source market analysis combining on-chain and community data', ARRAY['counsel', 'purposes', 'disappointed', 'counsellors', 'established']),
('If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.', 'James 1:5', 'wisdom_and_counsel', 'God gives wisdom freely to those who ask', 'Pray for wisdom in financial decisions', 'Biblical wisdom integration in every DeFi decision point', ARRAY['wisdom', 'ask', 'God', 'liberally', 'given']),
('How much better is it to get wisdom than gold! and to get understanding rather to be chosen than silver!', 'Proverbs 16:16', 'wisdom_and_counsel', 'Wisdom exceeds monetary wealth', 'Prioritize learning DeFi fundamentals over quick profits', 'Education-first approach: complete learning modules before advanced features', ARRAY['wisdom', 'gold', 'understanding', 'silver']),

-- PROSPERITY & BLESSING (new category)
('Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.', '3 John 1:2', 'prosperity_and_blessing', 'God desires our prosperity alongside spiritual health', 'Pursue financial growth that aligns with spiritual wellbeing', 'Holistic wealth dashboard tracking financial and Wisdom Score growth', ARRAY['prosper', 'health', 'soul', 'beloved']),
('The LORD maketh poor, and maketh rich: he bringeth low, and lifteth up.', '1 Samuel 2:7', 'prosperity_and_blessing', 'God is sovereign over financial outcomes', 'Trust God''s sovereignty while being diligent stewards', 'Accept market volatility while maintaining faithful stewardship', ARRAY['poor', 'rich', 'bringeth low', 'lifteth up']),
('And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work.', '2 Corinthians 9:8', 'prosperity_and_blessing', 'God provides sufficiency for generosity', 'Trust that faithful stewardship leads to sufficiency for giving', 'Yield optimization enables greater charitable allocation capacity', ARRAY['grace', 'abound', 'sufficiency', 'good work']),
('The LORD shall command the blessing upon thee in thy storehouses, and in all that thou settest thine hand unto.', 'Deuteronomy 28:8', 'prosperity_and_blessing', 'God blesses faithful work and storage', 'Trust God''s blessing on disciplined saving and investing', 'Staking and vault strategies blessed through faithful stewardship', ARRAY['blessing', 'storehouses', 'hand', 'command'])

ON CONFLICT DO NOTHING;
